USE DATABASE HR;

CREATE OR REPLACE USER AllAccessUser
LOGIN_NAME = 'PSAllAccessUser',
PASSWORD = 'Password1',
DEFAULT_NAMESPACE = 'EMPLOYEEDATA',
DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE OR REPLACE USER ItUser
LOGIN_NAME = 'PSItUser',
PASSWORD = 'Password1',
DEFAULT_NAMESPACE = 'EMPLOYEEDATA'
DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE OR REPLACE USER FinanceUser
LOGIN_NAME = 'PSFinanceUser',
PASSWORD = 'Password1',
DEFAULT_NAMESPACE = 'EMPLOYEEDATA'
DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE OR REPLACE USER MarketingUser
LOGIN_NAME = 'PSMarketingUser',
PASSWORD = 'Password1',
DEFAULT_NAMESPACE = 'EMPLOYEEDATA'
DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE OR REPLACE USER SalesUser
LOGIN_NAME = 'PSSalesUser',
PASSWORD = 'Password1',
DEFAULT_NAMESPACE = 'EMPLOYEEDATA'
DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE OR REPLACE USER TechnologyUser
LOGIN_NAME = 'PSTechnologyUser',
PASSWORD = 'Password1',
DEFAULT_NAMESPACE = 'EMPLOYEEDATA'
DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE OR REPLACE USER HumanResourcesUser
LOGIN_NAME = 'PSHumanResourcesUser',
PASSWORD = 'Password1',
DEFAULT_NAMESPACE = 'EMPLOYEEDATA'
DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE OR REPLACE USER OperationsUser
LOGIN_NAME = 'PSOperationsUser',
PASSWORD = 'Password1',
DEFAULT_NAMESPACE = 'EMPLOYEEDATA'
DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE OR REPLACE USER CustomerServiceUser
LOGIN_NAME = 'PSCustomerServiceUser',
PASSWORD = 'Password1',
DEFAULT_NAMESPACE = 'EMPLOYEEDATA'
DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE OR REPLACE USER ProductManagementUser
LOGIN_NAME = 'PSProductManagementUser',
PASSWORD = 'Password1',
DEFAULT_NAMESPACE = 'EMPLOYEEDATA'
DEFAULT_WAREHOUSE = COMPUTE_WH;

CREATE OR REPLACE USER AdministrationUser
LOGIN_NAME = 'PSAdministrationUser',
PASSWORD = 'Password1',
DEFAULT_NAMESPACE = 'EMPLOYEEDATA'
DEFAULT_WAREHOUSE = COMPUTE_WH;
