CREATE OR REPLACE ROLE HR_ALL_ACCESS
COMMENT = 'Access to all HR objects';

CREATE OR REPLACE ROLE HR_IT_ACCESS
COMMENT = 'Access to IT-related HR objects';

CREATE OR REPLACE ROLE HR_FINANCE_ACCESS
COMMENT = 'Access to Finance-related HR objects';

CREATE OR REPLACE ROLE HR_MARKETING_ACCESS
COMMENT = 'Access to Marketing-related HR objects';

CREATE OR REPLACE ROLE HR_SALES_ACCESS
COMMENT = 'Access to Sales-related HR objects';

CREATE OR REPLACE ROLE HR_TECHNOLOGY_ACCESS
COMMENT = 'Access to Technology-related HR objects';

CREATE OR REPLACE ROLE HR_HUMANRESOURCES_ACCESS
COMMENT = 'Access to Human Resources-related HR objects';

CREATE OR REPLACE ROLE HR_OPERATIONS_ACCESS
COMMENT = 'Access to Operations-related HR objects';

CREATE OR REPLACE ROLE HR_CUSTOMERSERVICE_ACCESS
COMMENT = 'Access to Customer Service-related HR objects';

CREATE OR REPLACE ROLE HR_PRODUCTMANAGEMENT_ACCESS
COMMENT = 'Access to Product Management-related HR objects';

CREATE OR REPLACE ROLE HR_ADMINISTRATION_ACCESS
COMMENT = 'Access to Administration-related HR objects';

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO HR_ALL_ACCESS;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO HR_IT_ACCESS;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO HR_FINANCE_ACCESS;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO HR_MARKETING_ACCESS;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO HR_SALES_ACCESS;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO HR_TECHNOLOGY_ACCESS;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO HR_HUMANRESOURCES_ACCESS;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO HR_OPERATIONS_ACCESS;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO HR_CUSTOMERSERVICE_ACCESS;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO HR_PRODUCTMANAGEMENT_ACCESS;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO HR_ADMINISTRATION_ACCESS;

GRANT USAGE ON DATABASE HR TO ROLE HR_ALL_ACCESS;
GRANT USAGE ON DATABASE HR TO ROLE HR_IT_ACCESS;
GRANT USAGE ON DATABASE HR TO ROLE HR_FINANCE_ACCESS;
GRANT USAGE ON DATABASE HR TO ROLE HR_MARKETING_ACCESS;
GRANT USAGE ON DATABASE HR TO ROLE HR_SALES_ACCESS;
GRANT USAGE ON DATABASE HR TO ROLE HR_TECHNOLOGY_ACCESS;
GRANT USAGE ON DATABASE HR TO ROLE HR_HUMANRESOURCES_ACCESS;
GRANT USAGE ON DATABASE HR TO ROLE HR_OPERATIONS_ACCESS;
GRANT USAGE ON DATABASE HR TO ROLE HR_CUSTOMERSERVICE_ACCESS;
GRANT USAGE ON DATABASE HR TO ROLE HR_PRODUCTMANAGEMENT_ACCESS;
GRANT USAGE ON DATABASE HR TO ROLE HR_ADMINISTRATION_ACCESS;

GRANT USAGE ON SCHEMA HR.EMPLOYEEDATA TO ROLE HR_ALL_ACCESS;
GRANT USAGE ON SCHEMA HR.EMPLOYEEDATA TO ROLE HR_IT_ACCESS;
GRANT USAGE ON SCHEMA HR.EMPLOYEEDATA TO ROLE HR_FINANCE_ACCESS;
GRANT USAGE ON SCHEMA HR.EMPLOYEEDATA TO ROLE HR_MARKETING_ACCESS;
GRANT USAGE ON SCHEMA HR.EMPLOYEEDATA TO ROLE HR_SALES_ACCESS;
GRANT USAGE ON SCHEMA HR.EMPLOYEEDATA TO ROLE HR_TECHNOLOGY_ACCESS;
GRANT USAGE ON SCHEMA HR.EMPLOYEEDATA TO ROLE HR_HUMANRESOURCES_ACCESS;
GRANT USAGE ON SCHEMA HR.EMPLOYEEDATA TO ROLE HR_OPERATIONS_ACCESS;
GRANT USAGE ON SCHEMA HR.EMPLOYEEDATA TO ROLE HR_CUSTOMERSERVICE_ACCESS;
GRANT USAGE ON SCHEMA HR.EMPLOYEEDATA TO ROLE HR_PRODUCTMANAGEMENT_ACCESS;
GRANT USAGE ON SCHEMA HR.EMPLOYEEDATA TO ROLE HR_ADMINISTRATION_ACCESS;
