USE DATABASE HR;

SELECT  EMPLOYEEID,
        EMPLOYEENAME,
        GENDER,
        DATEOFBIRTH,
        AGE,
        MARITALSTATUS,
        NATIONALITY,
        CITY,
        STATE,
        COUNTRY,
        JOBTITLE,
        DEPARTMENT,
        BUSINESSUNIT,
        DIVISION
    FROM EMPLOYEEDATA.EMPLOYEE;

CREATE OR REPLACE VIEW EMPLOYEEDATA.EMPLOYEEBUSINESSDATA
AS
SELECT  EMPLOYEEID,
        EMPLOYEENAME
        JOBTITLE,
        DEPARTMENT,
        BUSINESSUNIT,
        DIVISION
    FROM EMPLOYEEDATA.EMPLOYEE;

CREATE OR REPLACE VIEW EMPLOYEEDATA.EMPLOYEEPERSONALDATA
AS
SELECT  EMPLOYEEID,
        EMPLOYEENAME,
        GENDER,
        DATEOFBIRTH,
        AGE,
        MARITALSTATUS,
        NATIONALITY,
        CITY,
        STATE,
        COUNTRY,
        JOBTITLE
    FROM EMPLOYEEDATA.EMPLOYEE;

SELECT * 
    FROM EMPLOYEEDATA.EMPLOYEEPERSONALDATA;
SELECT * 
    FROM EMPLOYEEDATA.EMPLOYEEBUSINESSDATA;

CREATE OR REPLACE VIEW EMPLOYEEDATA.DEPARTMENTTRAINING_ALL
AS
SELECT  E.EMPLOYEEID,
        C.COURSENAME,
        EC.COMPLETIONSTATUS,
        EC.COMPLETIONDATE
    FROM EMPLOYEEDATA.EMPLOYEE E
        INNER JOIN EMPLOYEEDATA.EMPLOYEECOURSE EC
            ON E.EMPLOYEEID = EC.EMPLOYEEID
        INNER JOIN EMPLOYEEDATA.COURSE C
            ON EC.COURSEID = C.COURSEID;


SELECT *
    FROM EMPLOYEEDATA.DEPARTMENTTRAINING_ALL A
        INNER JOIN EMPLOYEEDATA.EMPLOYEEBUSINESSDATA EBD
            ON A.EMPLOYEEID = EBD.EMPLOYEEID;












