USE DATABASE HR;

CREATE OR REPLACE VIEW EMPLOYEEDATA.DEPARTMENTTRAINING_IT
AS
SELECT *
    FROM EMPLOYEEDATA.DEPARTMENTTRAINING_ALL
WHERE DEPARTMENT = 'IT';

SELECT *
    FROM EMPLOYEEDATA.DEPARTMENTTRAINING_IT;

CREATE OR REPLACE VIEW EMPLOYEEDATA.DEPARTMENTTRAINING_FINANCE
AS
SELECT *
    FROM EMPLOYEEDATA.DEPARTMENTTRAINING_ALL
WHERE DEPARTMENT = 'Finance';

SELECT *
    FROM EMPLOYEEDATA.DEPARTMENTTRAINING_FINANCE;

CREATE OR REPLACE VIEW EMPLOYEEDATA.DEPARTMENTTRAINING_MARKETING
AS
SELECT *
    FROM EMPLOYEEDATA.DEPARTMENTTRAINING_ALL
WHERE DEPARTMENT = 'Marketing';

CREATE OR REPLACE VIEW EMPLOYEEDATA.DEPARTMENTTRAINING_SALES
AS
SELECT *
    FROM EMPLOYEEDATA.DEPARTMENTTRAINING_ALL
WHERE DEPARTMENT = 'Sales';

CREATE OR REPLACE VIEW EMPLOYEEDATA.DEPARTMENTTRAINING_TECHNOLOGY
AS
SELECT *
    FROM EMPLOYEEDATA.DEPARTMENTTRAINING_ALL
WHERE DEPARTMENT = 'Technology';

CREATE OR REPLACE VIEW EMPLOYEEDATA.DEPARTMENTTRAINING_HUMANRESOURCES
AS
SELECT *
    FROM EMPLOYEEDATA.DEPARTMENTTRAINING_ALL
WHERE DEPARTMENT = 'Human Resources';

CREATE OR REPLACE VIEW EMPLOYEEDATA.DEPARTMENTTRAINING_OPERATIONS
AS
SELECT *
    FROM EMPLOYEEDATA.DEPARTMENTTRAINING_ALL
WHERE DEPARTMENT = 'Operations';

CREATE OR REPLACE VIEW EMPLOYEEDATA.DEPARTMENTTRAINING_CUSTOMERSERVICE
AS
SELECT *
    FROM EMPLOYEEDATA.DEPARTMENTTRAINING_ALL
WHERE DEPARTMENT = 'Customer Service';

CREATE OR REPLACE VIEW EMPLOYEEDATA.DEPARTMENTTRAINING_PRODUCTMANAGEMENT
AS
SELECT *
    FROM EMPLOYEEDATA.DEPARTMENTTRAINING_ALL
WHERE DEPARTMENT = 'Product Management';

CREATE OR REPLACE VIEW EMPLOYEEDATA.DEPARTMENTTRAINING_ADMINISTRATION
AS
SELECT *
    FROM EMPLOYEEDATA.DEPARTMENTTRAINING_ALL
WHERE DEPARTMENT = 'Administration';
