USE DATABASE HR;

GRANT ROLE HR_ALL_ACCESS TO USER ALLACCESSUSER;
GRANT ROLE HR_IT_ACCESS TO USER ITUSER;
GRANT ROLE HR_FINANCE_ACCESS TO USER FINANCEUSER;
GRANT ROLE HR_MARKETING_ACCESS TO USER MARKETINGUSER;
GRANT ROLE HR_SALES_ACCESS TO USER SALESUSER;
GRANT ROLE HR_TECHNOLOGY_ACCESS TO USER TECHNOLOGYUSER;
GRANT ROLE HR_HUMANRESOURCES_ACCESS TO USER HUMANRESOURCESUSER;
GRANT ROLE HR_OPERATIONS_ACCESS TO USER OPERATIONSUSER;
GRANT ROLE HR_CUSTOMERSERVICE_ACCESS TO USER CUSTOMERSERVICEUSER;
GRANT ROLE HR_PRODUCTMANAGEMENT_ACCESS TO USER PRODUCTMANAGEMENTUSER;
GRANT ROLE HR_ADMINISTRATION_ACCESS TO USER ADMINISTRATIONUSER;

GRANT SELECT ON VIEW EMPLOYEEDATA.DEPARTMENTTRAINING_IT TO ROLE HR_IT_ACCESS;

SHOW GRANTS TO ROLE HR_IT_ACCESS;