USE DATABASE HR;

ALTER VIEW IF EXISTS EMPLOYEEDATA.DEPARTMENTTRAINING_IT 
RENAME TO NEW_VIEW_NAME_GOES_HERE;

ALTER VIEW IF EXISTS EMPLOYEEDATA.DEPARTMENTTRAINING_IT 
SET COMMENT = 'Displays IT department employee training data';

ALTER VIEW IF EXISTS EMPLOYEEDATA.DEPARTMENTTRAINING_IT 
UNSET COMMENT;

ALTER VIEW EMPLOYEEDATA.DEPARTMENTTRAINING_IT 
SET SECURE;

DESCRIBE VIEW EMPLOYEEDATA.DEPARTMENTTRAINING_ALL;
DESCRIBE VIEW EMPLOYEEDATA.DEPARTMENTTRAINING_COURSECOMPLETIONTOTAL;